openapi: 3.0.0
info:
  title: Orchestrator API
  description: API that orchestrate all integrations
  version: 0.0.1
servers:
  - url: http://localhost:3001/v1
tags:
  - name: Targets
  - name: Graph
paths:
  /targets/register:
    post:
      tags:
        - Targets
      description: Register a new target
      summary: Register a new target
      requestBody:
        content:
          'application/json':
            schema:
              properties:
                host:
                  type: string
                  description: IP or Hostname of the target
                  example: example.com
                comment:
                  type: string
                  description: A comment
                  example: This is a HackTheBox machine
      responses:
        201:
          description: Registered
          content:
            'application/json':
              schema:
                properties:
                  uid:
                    type: string
                    description: Target uid
                    example: 161C6007-EC3F-4BF1-9A31-E0A753D76EB5
                  host:
                    type: string
                    description: IP or Hostname of the target
                    example: example.com

  /targets/{uid}:
    put:
      tags:
        - Targets
      description: Execute an action on the target
      parameters:
        - name: uid
          required: true
          in: path
          schema:
            type: string
            description: Target uid
      requestBody:
        content:
          'application/json':
            schema:
              properties:
                action:
                  description: Type of action to execute
                  type: string
                  enum:
                    - NET_SCAN
                    - WEB_PATH_DISCOVERY
                  example: NET_SCAN
                options:
                  oneOf:
                    - title: Nmap Scan - Network
                      properties:
                        service_version:
                          type: boolean
                          example: true
                        hosts_online:
                          type: boolean
                          example: false
                        port_range:
                          type: string
                          example: 22-443
                        default_scripts:
                          type: boolean
                          example: true
                        syn_scan:
                          type: boolean
                          example: false
                        udp_scan:
                          type: boolean
                          example: false
                    - title: Ffuf Scan - Web Path Discovery
                      properties:
                        start_node:
                          type: object
                          properties:
                            uid:
                              $ref: '#/components/schemas/Uid'
                            port:
                              type: number
                              description: Port number. HTTP = 80; HTTPS = 445
                              example: 445
                        recursion:
                          type: boolean
                          example: false
                        redirect:
                          type: boolean
                          example: true
                        ignore_status:
                          type: array
                          items:
                            type: number
                          example:
                            - 403
                            - 401

      responses:
        200:
          description: OK Execution
          content:
            'application/json':
              schema:
                properties:
                  data:
                    type: object

  /graph:
    get:
      tags:
        - Graph
      description: Get the graph from the database
      summary: Get the graph
      responses:
        200:
          description: Successful response
          content:
            'application/json':
              schema:
                properties:
                  nodes:
                    type: array
                    items:
                      properties:
                        name:
                          description: Node name
                          type: string
                        id:
                          description: Node id
                          type: string
                        label:
                          type: string
                        tags:
                          type: array
                          items:
                            type: string
                  edges:
                    type: array
                    items:
                      properties:
                        source:
                          type: string
                        target:
                          type: string
                        label:
                          description: Edge description
                          type: string

components:
  schemas:
    Uid:
      type: string
      description: Target uid
      example: 161C6007-EC3F-4BF1-9A31-E0A753D76EB5
