openapi: 3.0.0
info:
  title: Orchestrator API
  description: API that orchestrate all integrations
  version: 0.0.1
servers:
  - url: http://localhost:5001/v1

paths:
  /:
    get:
      summary: Some
      responses:
        200:
          description: OK
          content:
            'application/json': 
              schema:
                type: string
                example: Success
  
